# Generated by Django 4.2.1 on 2023-06-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default=-1, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
