# Generated by Django 4.2.1 on 2023-07-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='online',
            new_name='users',
        ),
    ]
