# Generated by Django 4.2.1 on 2023-06-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_user_salt'),
        ('Chat', '0002_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ManyToManyField(related_name='user1', to='Login.user')),
                ('user2', models.ManyToManyField(related_name='user2', to='Login.user')),
            ],
        ),
    ]
