# Generated by Django 4.2.1 on 2023-06-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_friend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
